theme: jekyll-theme-cayman

name: Nat's Paper Craft
title: null
description: null

logo_url: ./images/npc_logo_red_w500_t.png # Either absolute or relative url

google_analytics: G-G5JTDJBFC9
google_analytics_anonymize: false
