theme: jekyll-theme-cayman

title: [Nat's Paper Craft]
description: [Card Making :: Scrapbooking :: Stamping :: Embellishing]

logo_url: ./images/npc_logo_red_w500_t.png # Either absolute or relative url

google_analytics: [G-G5JTDJBFC9]
google_analytics_anonymize: false
